# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0002_auto_20180507_1136'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='axf_goods',
        ),
    ]
