# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0003_auto_20180507_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='ticket',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
