# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0004_usermodel_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=30)),
                ('max_age', models.IntegerField()),
            ],
        ),
    ]
