# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0008_auto_20180508_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='o_total',
            field=models.FloatField(default=0),
        ),
    ]
